### ISSUE TITLE
Highlighted link based on position

### ISSUE THREAD

**Issue by akeklak** [Brain-Arts-Git/brain_arts_site#2]
When you click on a link, it scrolls to a section.  However, if you don't scroll down any further, the section indicated on the nav bar is actually the section above the section you're currently looking at.  If you scroll down any amount, it highlights the correct link corresponding to the section you are on.

**Comment by jrodiger** [comment]
seems to only affect some of the links and isn't an issue when scrolling so I think this is pretty low priority

**Comment by jrodiger** [comment]
No longer using link highlighting
