### ISSUE TITLE
prevent caching of CSS files

### ISSUE THREAD

**Issue by akeklak** [Brain-Arts-Git/brain_arts_site#3]
site on local dev server stopped responding to changes made in the css file.  fixed by clearing cache, but its annoying to have to do that every time a change is made.  Not sure why it started happening suddenly.

**Comment by jrodiger** [comment]
browsers will do this automatically, on chrome if you open the inspect tab and then go to the network tab you can disable caching for testing. there should be a way to disable from within flask too, but I'm not sure how

**Comment by akeklak** [comment]
yeah i found that from the dev tools.  ill look up how to prevent it in flask, there's a way to basically version control all of the static files for when its released publicly but for dev i want something more convenient
