### ISSUE TITLE
blog -> homepage navigation

### ISSUE THREAD

**Issue by jrodiger** [Brain-Arts-Git/brain_arts_site#4]
two issues related to this:
- when returning to the homepage from the blog the url shows brain-arts.org/index when it should just be the base url
- when on the blog page clicking the brain arts logo on the nav bar takes you to the top of the page rather than back to the homepage. I think this behavior makes sense on the homepage, but is not intuitive on other pages

**Comment by akeklak** [comment]
I fixed the first thing

**Comment by akeklak** [comment]
both fixed now.

**Comment by linyu3294** [comment]
Hey guys, I'm working on studying for my Discrete Math finals.
I will try to catch up when I finish with my semester
